---
abstract: 'kill your broken Perl script'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::7 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Limit
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Time::Limit:
    file: lib/Time/Limit.pm
    version: '0.003'
requires:
  Time::HiRes: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Time-Limit/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Time-Limit
  homepage: https://metacpan.org/release/Time-Limit
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-time-limit.git
version: '0.003'
